### ISSUE TITLE
Provide a list of recent local searches for the user to select from when interacting with the search box

### ISSUE THREAD

**Issue by acron0** [WorksHub/client#44]
We would like users to be able to select, from a dropdown below the top navigation search box, recent searches.

![image](https://user-images.githubusercontent.com/812199/91825398-20256e80-ec34-11ea-9da6-47c259ca81bc.png)

![image](https://user-images.githubusercontent.com/812199/91826892-16046f80-ec36-11ea-91f6-2e8ef7b8a1ce.png)

* The search terms should be stored in local storage and therefore no backend support is required.
* Initially, when there is no search term entered, the last n searches should be displayed
* Once there is a search term (or part of a term), perform an "includes" filter on the list and only display the most recent matching n searches. Extra points if we can highlight the match within the search.
* This should work _without_ the ClojureScript app and therefore the solution to be written in JavaScript (there are plenty of examples of this within the project)
* Extra points for allowing the searches to be deleted

**Comment by ChaituVR** [comment]
@acron0 Is this still available to work..??? https://www.works-hub.com/issue/dcee1056-e32f-4513-bb04-7351a5162001 gives me 404 (not found)

**Comment by acron0** [comment]
@ChaituVR Yes, sorry we had some issues with issues (hah!) Should be fine now.

**Comment by rodmoioliveira** [comment]
@acron0, I'm working on this issue. But a had a problem with the server in development. In some point in time I started the server and began to get this error:

<img width="1792" alt="Captura de Tela 2020-09-24 às 22 58 06" src="https://user-images.githubusercontent.com/25094770/94217896-83b05e00-feb9-11ea-8b68-52b9642fa516.png">

This is the stack error:

```sh
user=> 2020-09-24 22:52:22.906:WARN:oejs.HttpChannel:qtp1418579907-56: /
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.quoteReplacement(Matcher.java:810)
	at clojure.string$replace_by.invokeStatic(string.clj:69)
	at clojure.string$replace.invokeStatic(string.clj:106)
	at clojure.string$replace.invoke(string.clj:75)
	at net.cgrand.enlive_html$replace_vars$substitute_vars__7144.invoke(enlive_html.clj:677)
	at net.cgrand.enlive_html$replace_vars$fn__7146.invoke(enlive_html.clj:680)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$seq__5387.invoke(core.clj:137)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___6646.invoke(enlive_html.clj:228)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat__6652$fn__6653.invoke(enlive_html.clj:233)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$seq__5387.invoke(core.clj:137)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at clojure.zip$children.invokeStatic(zip.clj:80)
	at clojure.zip$down.invokeStatic(zip.clj:115)
	at clojure.zip$down.invoke(zip.clj:109)
	at net.cgrand.enlive_html$children_locs.invokeStatic(enlive_html.clj:418)
	at net.cgrand.enlive_html$children_locs.invoke(enlive_html.clj:417)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:427)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_loc$fn__6872.invoke(enlive_html.clj:426)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:426)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_loc$fn__6872.invoke(enlive_html.clj:426)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:426)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_node$fn__6881.invoke(enlive_html.clj:442)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_node.invokeStatic(enlive_html.clj:442)
	at net.cgrand.enlive_html$transform_node.invoke(enlive_html.clj:438)
	at net.cgrand.enlive_html$transform.invokeStatic(enlive_html.clj:486)
	at net.cgrand.enlive_html$transform.invoke(enlive_html.clj:481)
	at wh.server$fn__11109$fn__11112$fn__11114.invoke(server.clj:66)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$next__5371.invoke(core.clj:64)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___6646.invoke(enlive_html.clj:228)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat__6652$fn__6653.invoke(enlive_html.clj:233)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at wh.server$fn__11109$fn__11112.invoke(server.clj:66)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at wh.server$index_handler.invokeStatic(server.clj:114)
	at wh.server$index_handler.invoke(server.clj:113)
	at bidi.ring$eval2871$fn__2872.invoke(ring.cljc:25)
	at bidi.ring$eval2850$fn__2851$G__2841__2860.invoke(ring.cljc:16)
	at bidi.ring$make_handler$fn__2880.invoke(ring.cljc:43)
	at ring.middleware.resource$wrap_resource$fn__2832.invoke(resource.clj:37)
	at ring.middleware.content_type$wrap_content_type$fn__2574.invoke(content_type.clj:34)
	at clojure.lang.Var.invoke(Var.java:384)
	at ring.adapter.jetty$proxy_handler$fn__7498.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-24 22:52:23.031:WARN:oejs.HttpChannel:qtp1418579907-58: /favicon.ico
java.lang.NullPointerException: Response map is nil
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__7498.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-24 22:58:02.735:WARN:oejs.HttpChannel:qtp1418579907-57: /
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.quoteReplacement(Matcher.java:810)
	at clojure.string$replace_by.invokeStatic(string.clj:69)
	at clojure.string$replace.invokeStatic(string.clj:106)
	at clojure.string$replace.invoke(string.clj:75)
	at net.cgrand.enlive_html$replace_vars$substitute_vars__7144.invoke(enlive_html.clj:677)
	at net.cgrand.enlive_html$replace_vars$fn__7146.invoke(enlive_html.clj:680)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$seq__5387.invoke(core.clj:137)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___6646.invoke(enlive_html.clj:228)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat__6652$fn__6653.invoke(enlive_html.clj:233)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$seq__5387.invoke(core.clj:137)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at clojure.zip$children.invokeStatic(zip.clj:80)
	at clojure.zip$down.invokeStatic(zip.clj:115)
	at clojure.zip$down.invoke(zip.clj:109)
	at net.cgrand.enlive_html$children_locs.invokeStatic(enlive_html.clj:418)
	at net.cgrand.enlive_html$children_locs.invoke(enlive_html.clj:417)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:427)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_loc$fn__6872.invoke(enlive_html.clj:426)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:426)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_loc$fn__6872.invoke(enlive_html.clj:426)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_loc.invokeStatic(enlive_html.clj:426)
	at net.cgrand.enlive_html$transform_loc.invoke(enlive_html.clj:423)
	at net.cgrand.enlive_html$transform_node$fn__6881.invoke(enlive_html.clj:442)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at net.cgrand.enlive_html$mapknitv.invokeStatic(enlive_html.clj:200)
	at net.cgrand.enlive_html$mapknitv.invoke(enlive_html.clj:199)
	at net.cgrand.enlive_html$transform_node.invokeStatic(enlive_html.clj:442)
	at net.cgrand.enlive_html$transform_node.invoke(enlive_html.clj:438)
	at net.cgrand.enlive_html$transform.invokeStatic(enlive_html.clj:486)
	at net.cgrand.enlive_html$transform.invoke(enlive_html.clj:481)
	at wh.server$fn__11109$fn__11112$fn__11114.invoke(server.clj:66)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$next__5371.invoke(core.clj:64)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat_STAR___6646.invoke(enlive_html.clj:228)
	at net.cgrand.enlive_html$flatten_nodes_coll$flat__6652$fn__6653.invoke(enlive_html.clj:233)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at wh.server$fn__11109$fn__11112.invoke(server.clj:66)
	at clojure.core$comp$fn__5792.invoke(core.clj:2569)
	at wh.server$index_handler.invokeStatic(server.clj:114)
	at wh.server$index_handler.invoke(server.clj:113)
	at bidi.ring$eval2871$fn__2872.invoke(ring.cljc:25)
	at bidi.ring$eval2850$fn__2851$G__2841__2860.invoke(ring.cljc:16)
	at bidi.ring$make_handler$fn__2880.invoke(ring.cljc:43)
	at ring.middleware.resource$wrap_resource$fn__2832.invoke(resource.clj:37)
	at ring.middleware.content_type$wrap_content_type$fn__2574.invoke(content_type.clj:34)
	at clojure.lang.Var.invoke(Var.java:384)
	at ring.adapter.jetty$proxy_handler$fn__7498.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-24 22:58:02.947:WARN:oejs.HttpChannel:qtp1418579907-56: /favicon.ico
java.lang.NullPointerException: Response map is nil
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__7498.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

What should I do?

**Comment by acron0** [comment]
@rodmoioliveira Apologies. Can you try pulling from upstream master? We have encountered a problem in production yesterday which could be the cause of this. If not then I will investigate further.

**Comment by Iiqbal2000** [comment]
when i run with lein there is no problem, but when i run it using npm i get problem. 

as follows:

 ```[:app] Compiling ...
[0] [:app] Build failure:
[0] ------ ERROR -------------------------------------------------------------------
[0]  File: /home/pacol/coding/git/open-source-contribute/client/common-pages/src/wh/blogs/blog/events.cljc:34:1
[0] --------------------------------------------------------------------------------
[0]   31 | 
[0]   32 | (reg-query :blog blog-query)
[0]   33 | 
[0]   34 | (defquery recommendations-query
[0] -------^------------------------------------------------------------------------
[0] Encountered error when macroexpanding wh.graphql-macros/defquery.
[0] Invalid fragments: #{"jobCardFields"}
[0] {:venia/ex-type :venia/invalid-fragments, :venia/ex-data #{"jobCardFields"}}
[0] ExceptionInfo: Invalid fragments: #{"jobCardFields"}
[0] 	venia.exception/eval30707/fn--30708 (exception.cljc:15)
[0] 	clojure.lang.MultiFn.invoke (MultiFn.java:229)
[0] 	venia.spec/valid-fragments (spec.cljc:47)
[0] 	venia.spec/valid-fragments (spec.cljc:41)
[0] 	clojure.spec.alpha/spec-impl/reify--2059 (alpha.clj:923)
[0] 	clojure.spec.alpha/and-spec-impl/fn--2179 (alpha.clj:1163)
[0] 	clojure.spec.alpha/and-spec-impl/reify--2183 (alpha.clj:1183)
[0] 	clojure.spec.alpha/conform (alpha.clj:164)
[0] 	clojure.spec.alpha/conform (alpha.clj:160)
[0] 	venia.spec/query->spec (spec.cljc:181)
[0] 	venia.spec/query->spec (spec.cljc:180)
[0] 	venia.core/graphql-query (core.cljc:229)
[0] 	venia.core/graphql-query (core.cljc:226)
[0] 	wh.graphql-macros/defquery (graphql_macros.clj:31)
[0] 	wh.graphql-macros/defquery (graphql_macros.clj:28)
[0] 	clojure.core/apply (core.clj:669)
[0] 	clojure.core/apply (core.clj:660)
[0] 	cljs.analyzer/macroexpand-1*/fn--2556 (analyzer.cljc:3879)
[0] 	cljs.analyzer/macroexpand-1* (analyzer.cljc:3877)
[0] 	cljs.analyzer/macroexpand-1* (analyzer.cljc:3864)
[0] 	cljs.analyzer/macroexpand-1 (analyzer.cljc:3928)
[0] 	cljs.analyzer/macroexpand-1 (analyzer.cljc:3924)
[0] 	cljs.analyzer/analyze-seq (analyzer.cljc:3961)
[0] 	cljs.analyzer/analyze-seq (analyzer.cljc:3941)
[0] 	cljs.analyzer/analyze-form (analyzer.cljc:4150)
[0] 	cljs.analyzer/analyze-form (analyzer.cljc:4147)
[0] 	cljs.analyzer/analyze* (analyzer.cljc:4200)
[0] 	cljs.analyzer/analyze* (analyzer.cljc:4191)
[0] 	shadow.build.compiler/analyze/fn--12110 (compiler.clj:250)
[0] 	shadow.build.compiler/analyze (compiler.clj:238)
[0] 	shadow.build.compiler/analyze (compiler.clj:197)
[0] 	shadow.build.compiler/analyze (compiler.clj:199)
[0] 	shadow.build.compiler/analyze (compiler.clj:197)
[0] 	shadow.build.compiler/default-analyze-cljs (compiler.clj:365)
[0] 	shadow.build.compiler/default-analyze-cljs (compiler.clj:354)
[0] 	clojure.core/partial/fn--5839 (core.clj:2625)
[0] 	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:306)
[0] 	shadow.build.compiler/do-analyze-cljs-string (compiler.clj:264)
[0] 	shadow.build.compiler/analyze-cljs-string/fn--12179 (compiler.clj:466)
[0] 	shadow.build.compiler/analyze-cljs-string (compiler.clj:465)
[0] 	shadow.build.compiler/analyze-cljs-string (compiler.clj:463)
[0] 	shadow.build.compiler/do-compile-cljs-resource/fn--12207 (compiler.clj:580)
[0] 	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:562)
[0] 	shadow.build.compiler/do-compile-cljs-resource (compiler.clj:520)
[0] 	shadow.build.compiler/maybe-compile-cljs/fn--12305 (compiler.clj:897)
[0] 	shadow.build.compiler/maybe-compile-cljs (compiler.clj:896)
[0] 	shadow.build.compiler/maybe-compile-cljs (compiler.clj:872)
[0] 	shadow.build.compiler/par-compile-one (compiler.clj:1005)
[0] 	shadow.build.compiler/par-compile-one (compiler.clj:960)
[0] 	shadow.build.compiler/par-compile-cljs-sources/fn--12341/iter--12363--12367/fn--12368/fn--12369/fn--12370 (compiler.clj:1078)
[0] 	clojure.core/apply (core.clj:665)
[0] 	clojure.core/with-bindings* (core.clj:1973)
[0] 	clojure.core/with-bindings* (core.clj:1973)
[0] 	clojure.core/apply (core.clj:669)
[0] 	clojure.core/bound-fn*/fn--5749 (core.clj:2003)
[0] 	java.util.concurrent.FutureTask.run (FutureTask.java:264)
[0] 	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
[0] 	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
[0] 	java.lang.Thread.run (Thread.java:834)
[0] 
[0] --------------------------------------------------------------------------------
[0]   35 |   {:venia/operation {:operation/type :query
[0]   36 |                      :operation/name "recommended_jobs"}
[0]   37 |    :venia/variables [{:variable/name "id"
[0]   38 |                       :variable/type :ID}
[0] --------------------------------------------------------------------------------
```

**Comment by acron0** [comment]
@Iiqbal2000 Which `npm` command do you use? @nathell Might be able to shed some light on this, but I usually find a `lein clean` sorts out the problem

**Comment by Iiqbal2000** [comment]
I use `npm run dev`
