### ISSUE TITLE
Unexplained 500 errors in our development server

### ISSUE THREAD

**Issue by acron0** [WorksHub/client#47]
When running the development server for this project, resources like `/favicon.ico` are triggering 500s rather than 404s. Here is a stack trace which is being logged which indicates the 'cause' of the 500. As you can see, it's not within our server code and somehow related to resources.

```
2020-11-25 14:39:11.822:WARN:oejs.HttpChannel:qtp505036866-44: /favicon.ico
java.lang.NullPointerException: Response map is nil
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:100)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__13225.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```
![image](https://user-images.githubusercontent.com/812199/100242085-4ead9f80-2f2c-11eb-956d-1cb5100d5f02.png)

This create a lot of noise in the development server, which is not ideal! Missing resources should be handled as 404s, not 500s.

Follow the instructions [here](https://github.com/WorksHub/client#getting-started) to get the server started. You do not need to log in to reproduce this.

**Comment by acron0** [comment]
Thank you @dmarjenburgh!
